CREATE TABLE PROPRIEDADE (
    id INTEGER PRIMARY KEY auto_increment,
    descricao VARCHAR(64) NOT NULL,
    estado VARCHAR(1) NOT NULL  DEFAULT 'A'
);

CREATE TABLE LABORATORIO (
    id INTEGER PRIMARY KEY auto_increment,
    descricao VARCHAR(64) NOT NULL,
    estado VARCHAR(1) NOT NULL DEFAULT 'A'
);

CREATE TABLE PESSOA_LABORATORIO (
    id INTEGER PRIMARY KEY auto_increment,
    nome VARCHAR(64) NOT NULL,
    dt_inicio DATE NOT NULL,
    dt_fim DATE NOT NULL,
    propriedade_id INTEGER NOT NULL,
    laboratorio_id INTEGER NOT NULL,
    observacoes VARCHAR(200) NOT NULL,
    estado VARCHAR(1) NOT NULL DEFAULT 'A'
);

ALTER TABLE PESSOA_LABORATORIO
    ADD FOREIGN KEY (propriedade_id)
        REFERENCES PROPRIEDADE(id);

ALTER TABLE PESSOA_LABORATORIO
    ADD FOREIGN KEY (laboratorio_id)
        REFERENCES LABORATORIO(id);
